import { RANKING_CLASS, RANKING_SPEC } from '../constants'

const rankingClassColorMap = {
    [RANKING_CLASS.MAGE]: '#40C7EB',
    [RANKING_CLASS.WARRIOR]: '#C79C6E',
    [RANKING_CLASS.DRUID]: '#FF7D0A',
    [RANKING_CLASS.HUNTER]: '#A9D271',
    [RANKING_CLASS.PALADIN]: '#F58CBA',
    [RANKING_CLASS.PRIEST]: '#FFFFFF',
    [RANKING_CLASS.ROGUE]: '#FFF569',
    [RANKING_CLASS.SHAMAN]: '#0070DE',
    [RANKING_CLASS.WARLOCK]: '#8787ED',
}

const classSpecToIconIndexMap: { [key: string]: number } = {
    [`${RANKING_CLASS.DRUID}-${RANKING_SPEC.BALANCE}`]: 12,
    [`${RANKING_CLASS.DRUID}-${RANKING_SPEC.FERAL}`]: 14,
    [`${RANKING_CLASS.DRUID}-${RANKING_SPEC.TANK}`]: 15,
    [`${RANKING_CLASS.DRUID}-${RANKING_SPEC.RESTORATION}`]: 16,
    [`${RANKING_CLASS.HUNTER}-${RANKING_SPEC.BEAST_MASTERY}`]: 24,
    [`${RANKING_CLASS.HUNTER}-${RANKING_SPEC.MARKSMANSHIP}`]: 25,
    [`${RANKING_CLASS.HUNTER}-${RANKING_SPEC.MELEE}`]: 26,
    [`${RANKING_CLASS.MAGE}-${RANKING_SPEC.ARCANE}`]: 30,
    [`${RANKING_CLASS.MAGE}-${RANKING_SPEC.FIRE}`]: 31,
    [`${RANKING_CLASS.MAGE}-${RANKING_SPEC.FROST}`]: 32,
    [`${RANKING_CLASS.MAGE}-${RANKING_SPEC.HEALER}`]: 33,
    [`${RANKING_CLASS.PALADIN}-${RANKING_SPEC.HOLY}`]: 41,
    [`${RANKING_CLASS.PALADIN}-${RANKING_SPEC.PROTECTION}`]: 43,
    [`${RANKING_CLASS.PALADIN}-${RANKING_SPEC.RETRIBUTION}`]: 44,
    [`${RANKING_CLASS.PRIEST}-${RANKING_SPEC.DISCIPLINE}`]: 47,
    [`${RANKING_CLASS.PRIEST}-${RANKING_SPEC.HOLY}`]: 49,
    [`${RANKING_CLASS.PRIEST}-${RANKING_SPEC.SHADOW}`]: 50,
    [`${RANKING_CLASS.ROGUE}-${RANKING_SPEC.ASSASSINATION}`]: 53,
    [`${RANKING_CLASS.ROGUE}-${RANKING_SPEC.SUBTELTY}`]: 57,
    [`${RANKING_CLASS.ROGUE}-${RANKING_SPEC.TANK}`]: 58,
    [`${RANKING_CLASS.SHAMAN}-${RANKING_SPEC.ELEMENTAL}`]: 60,
    [`${RANKING_CLASS.SHAMAN}-${RANKING_SPEC.ENHANCEMENT}`]: 61,
    [`${RANKING_CLASS.SHAMAN}-${RANKING_SPEC.RESTORATION}`]: 62,
    [`${RANKING_CLASS.SHAMAN}-${RANKING_SPEC.TANK}`]: 63,
    [`${RANKING_CLASS.WARLOCK}-${RANKING_SPEC.AFFLICTION}`]: 67,
    [`${RANKING_CLASS.WARLOCK}-${RANKING_SPEC.DEMONOLOGY}`]: 68,
    [`${RANKING_CLASS.WARLOCK}-${RANKING_SPEC.DESTRUCTION}`]: 69,
    [`${RANKING_CLASS.WARLOCK}-${RANKING_SPEC.TANK}`]: 71,
    [`${RANKING_CLASS.WARRIOR}-${RANKING_SPEC.FURY}`]: 75,
    [`${RANKING_CLASS.WARRIOR}-${RANKING_SPEC.ARMS}`]: 73,
    [`${RANKING_CLASS.WARRIOR}-${RANKING_SPEC.TANK}`]: 78,
}

const classToSpecMap = {
    [RANKING_CLASS.DRUID]: [
        RANKING_SPEC.BALANCE,
        RANKING_SPEC.FERAL,
        RANKING_SPEC.RESTORATION,
    ],
    [RANKING_CLASS.HUNTER]: [
        RANKING_SPEC.BEAST_MASTERY,
        RANKING_SPEC.MARKSMANSHIP,
        RANKING_SPEC.MELEE,
    ],
}

export const getRankingClassColor = (rankingClass: RANKING_CLASS): string => {
    return rankingClassColorMap[rankingClass] || '#FFFFFF'
}

export const getSpecIconIndex = (
    characterClass: RANKING_CLASS,
    spec: RANKING_SPEC
): number => {
    const key = `${characterClass}-${spec}`
    return classSpecToIconIndexMap[key] || -1
}
