services:
  app:
    image: wow-app
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgresql:14.0
    environment:
      POSTGRESQL_DATABASE: 'wow-app-db'
      POSTGRES_USER: 'WowAppAdm'
      POSTGRES_PASSWORD: 'WowAppDB123'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
