services:
  app:
    image: wow-app
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - REMOVED
      - REMOVED
      - REMOVED
    volumes:
      - ../database:/init_db.d

volumes:
  postgres_data:
