services:
  app:
    image: wow-app
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://WowAppAdm:WowAppDB123!@db:5432/WowAppDb
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - REMOVED
      - REMOVED
      - REMOVED
    volumes:
      - ../database:/init_db.d

volumes:
  postgres_data:
