services:
  app:
    image: wow-app
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'wow-app-db'
      MYSQL_USER: 'WowAppAdm'
      MYSQL_PASSWORD: 'WowAppDB123'
      MYSQL_ROOT_PASSWORD: 'spooned91'
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
