FROM node:19 AS builder

WORKDIR /app

COPY package.json /app
COPY yarn.lock /app

RUN yarn install

COPY . /app

RUN yarn build

FROM node:19-alpine

WORKDIR /app

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/.env.docker ./.env.local
COPY --from=builder /app/docker/docker_scripts/start.sh ./start.sh
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/clearDB.sh ./clearDB.sh

RUN chmod +x /app/start.sh

RUN export $(cat ./.env.local | xargs)

ENTRYPOINT ["/app/start.sh"]
# CMD ["yarn", "start"]